/* tslint:disable */// Generated by Haxe TypeScript Declaration Generator :)

export class sdd_MediaObjectRef {
	constructor(ref: string);
	ref: string;
}

export class sdd_Representation {
	constructor(label: string, detail: string, mediaObjectsRefs?: sdd_MediaObjectRef[]);
	label: string;
	detail: string;
	mediaObjectsRefs: sdd_MediaObjectRef[];
	static _hx_skip_constructor: boolean;
}

export class sdd_StateRef {
	constructor(ref: string);
	ref: string;
}

export class sdd_CategoricalRef {
	constructor(ref: string, stateRefs: sdd_StateRef[]);
	ref: string;
	stateRefs: sdd_StateRef[];
}

export class sdd_Taxon extends sdd_Representation {
	constructor(id: string, parentId: string|undefined, representation: sdd_Representation, childrenIds?: string[], categoricals?: sdd_CategoricalRef[]);
	id: string;
	hid: string;
	parentId: string|undefined;
	categoricals: sdd_CategoricalRef[];
	childrenIds: string[];
}

export class sdd_State extends sdd_Representation {
	constructor(id: string, characterId: string, representation: sdd_Representation);
	id: string;
	characterId: string;
}

export class sdd_Character extends sdd_Representation {
	constructor(id: string, parentId: string|undefined, representation: sdd_Representation, states?: sdd_State[], inapplicableStatesRefs?: sdd_StateRef[], childrenIds?: string[]);
	id: string;
	states: sdd_State[];
	inapplicableStatesRefs: sdd_StateRef[];
	parentId: string|undefined;
	childrenIds: string[];
}

export class sdd_MediaObject {
	constructor(id: string, source: string, label: string, detail: string);
	id: string;
	source: string;
	label: string;
	detail: string;
}

export class sdd_Dataset {
	constructor(taxons: sdd_Taxon[], characters: sdd_Character[], states: sdd_State[], mediaObjects: sdd_MediaObject[]);
	taxons: sdd_Taxon[];
	characters: sdd_Character[];
	states: sdd_State[];
	mediaObjects: sdd_MediaObject[];
}

export class sdd_Loader {
	constructor(strictMode: boolean);
	readonly exceptionLog: string[];
	load(text: string): sdd_Dataset[];
}

export class sdd_Saver {
	constructor(datasets: sdd_Dataset[]);
	datasets: sdd_Dataset[];
	mediaObjectsCount: number;
	save(): string;
}